name: 'David Shipko, Writer'
favicon: null
layout_spectrum: 0.27391
typography_spectrum: 1
title: 'David Shipko, Writer'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#070707'
    - '#4f4641'
    - '#e5dcd5'
    - '#9b948c'
    - '#b7b0a6'
  brandStrength: 0.5
  lightness: 0.75
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
