name: 'David Shipko, Writer'
favicon: null
layout_spectrum: 0.48104
typography_spectrum: 0.4482036316767335
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.5
  lightness: 0.8811062385793775
  saturation: 0.6579769763629884
  rhythmicContrast: 0.3513732310384512
purpose: []
